-- Seed data for Project Jekyll & Hyde
-- Run this AFTER running schema.sql

-- Note: UUIDs will be auto-generated. You'll need to use the actual owner_id from your authenticated users.
-- For testing, we'll create some sample profiles first, then projects.

-- Sample Profiles
-- Replace these with your actual user UUIDs from Supabase Auth after signing up

-- Sample profile 1: Computer Science Student
INSERT INTO profiles (first_name, last_name, email, language, major, interests, skills, experience_level, availability, urls, bio_embedding)
VALUES (
    'Alice',
    'Johnson',
    'alice@example.com',
    'en',
    'Computer Science',
    'AI, Machine Learning, Web Development',
    ARRAY['Python', 'JavaScript', 'React', 'TensorFlow'],
    'intermediate',
    '{"hours_per_week": 15, "timezone": "PST"}'::jsonb,
    '{"github": "https://github.com/alicejohnson", "linkedin": "https://linkedin.com/in/alicejohnson"}'::jsonb,
    -- Using a zero vector for now - in production this would be generated by the API
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector
);

-- Sample profile 2: Biology Major
INSERT INTO profiles (first_name, last_name, email, language, major, interests, skills, experience_level, availability, urls, bio_embedding)
VALUES (
    'Bob',
    'Chen',
    'bob@example.com',
    'en',
    'Biology',
    'Bioinformatics, Research, Data Analysis',
    ARRAY['R', 'Python', 'Statistics', 'Lab Work'],
    'advanced',
    '{"hours_per_week": 20, "timezone": "EST"}'::jsonb,
    '{"github": "https://github.com/bobchen", "linkedin": "https://linkedin.com/in/bobchen"}'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector
);

-- Sample profile 3: Design Student
INSERT INTO profiles (first_name, last_name, email, language, major, interests, skills, experience_level, availability, urls, bio_embedding)
VALUES (
    'Carol',
    'Davis',
    'carol@example.com',
    'en',
    'Design',
    'UI/UX, Mobile Apps, Branding',
    ARRAY['Figma', 'Sketch', 'Adobe XD', 'Prototyping'],
    'intermediate',
    '{"hours_per_week": 10, "timezone": "CST"}'::jsonb,
    '{"linkedin": "https://linkedin.com/in/caroldavis", "discord": "carol#1234"}'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector
);

-- Sample profile 4: Backend Developer
INSERT INTO profiles (first_name, last_name, email, language, major, interests, skills, experience_level, availability, urls, bio_embedding)
VALUES (
    'David',
    'Williams',
    'david@example.com',
    'en',
    'Software Engineering',
    'Backend Development, APIs, Cloud Infrastructure',
    ARRAY['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'AWS'],
    'expert',
    '{"hours_per_week": 12, "timezone": "PST"}'::jsonb,
    '{"github": "https://github.com/davidwilliams", "linkedin": "https://linkedin.com/in/davidwilliams"}'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector
);

-- Sample Projects
-- Using the first profile as the owner for these projects

-- Project 1: AI Study Assistant
INSERT INTO projects (owner_id, title, description, tags, roadmap, project_embedding, status)
VALUES (
    (SELECT id FROM profiles WHERE email = 'alice@example.com'),
    'AI-Powered Study Assistant',
    'A mobile app that uses AI to help students study more effectively. It generates practice questions, summarizes notes, and tracks progress. Looking for a backend developer and a mobile designer.',
    ARRAY['ai', 'education', 'mobile', 'machine-learning'],
    '{
        "frontend": [
            {"task": "Design mobile UI mockups", "priority": "high", "estimated_hours": 12},
            {"task": "Implement React Native components", "priority": "high", "estimated_hours": 24}
        ],
        "backend": [
            {"task": "Set up FastAPI endpoints", "priority": "high", "estimated_hours": 16},
            {"task": "Integrate OpenAI API", "priority": "high", "estimated_hours": 8}
        ],
        "database": [
            {"task": "Design user and study session schema", "priority": "high", "estimated_hours": 6}
        ],
        "estimated_total_hours": 66,
        "difficulty": "intermediate"
    }'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector,
    'open'
);

-- Project 2: Health Tracking App
INSERT INTO projects (owner_id, title, description, tags, roadmap, project_embedding, status)
VALUES (
    (SELECT id FROM profiles WHERE email = 'bob@example.com'),
    'Personal Health Data Visualizer',
    'A web application that helps users track and visualize their health metrics over time. Connect with fitness trackers and provide insights. Need frontend developers and data visualization experts.',
    ARRAY['health', 'data-visualization', 'web', 'analytics'],
    '{
        "frontend": [
            {"task": "Create dashboard with charts", "priority": "high", "estimated_hours": 20},
            {"task": "Implement data import features", "priority": "medium", "estimated_hours": 12}
        ],
        "backend": [
            {"task": "Build REST API for health data", "priority": "high", "estimated_hours": 16},
            {"task": "Integrate with fitness APIs", "priority": "medium", "estimated_hours": 10}
        ],
        "database": [
            {"task": "Design time-series data schema", "priority": "high", "estimated_hours": 8}
        ],
        "estimated_total_hours": 66,
        "difficulty": "intermediate"
    }'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector,
    'open'
);

-- Project 3: Campus Event Finder
INSERT INTO projects (owner_id, title, description, tags, roadmap, project_embedding, status)
VALUES (
    (SELECT id FROM profiles WHERE email = 'carol@example.com'),
    'Campus Event Discovery Platform',
    'A mobile app to discover and share campus events. Features include event recommendations, RSVPs, and social sharing. Looking for full-stack developers.',
    ARRAY['social', 'mobile', 'events', 'community'],
    '{
        "frontend": [
            {"task": "Design event cards and feed", "priority": "high", "estimated_hours": 16},
            {"task": "Implement map integration", "priority": "medium", "estimated_hours": 12}
        ],
        "backend": [
            {"task": "Create event and user APIs", "priority": "high", "estimated_hours": 18},
            {"task": "Implement recommendation engine", "priority": "medium", "estimated_hours": 14}
        ],
        "database": [
            {"task": "Design event and attendance schema", "priority": "high", "estimated_hours": 6}
        ],
        "estimated_total_hours": 66,
        "difficulty": "intermediate"
    }'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector,
    'open'
);

-- Project 4: Code Snippet Manager
INSERT INTO projects (owner_id, title, description, tags, roadmap, project_embedding, status)
VALUES (
    (SELECT id FROM profiles WHERE email = 'david@example.com'),
    'Personal Code Snippet Organizer',
    'A web app for developers to save, organize, and search code snippets with syntax highlighting and tags. Need a frontend developer with React experience.',
    ARRAY['developer-tools', 'web', 'productivity', 'code'],
    '{
        "frontend": [
            {"task": "Build snippet editor with syntax highlighting", "priority": "high", "estimated_hours": 20},
            {"task": "Implement search and tagging", "priority": "high", "estimated_hours": 14}
        ],
        "backend": [
            {"task": "Create CRUD API for snippets", "priority": "high", "estimated_hours": 12},
            {"task": "Implement full-text search", "priority": "medium", "estimated_hours": 8}
        ],
        "database": [
            {"task": "Design snippet storage schema", "priority": "high", "estimated_hours": 4}
        ],
        "estimated_total_hours": 58,
        "difficulty": "beginner"
    }'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector,
    'open'
);

-- Project 5: Sustainability Tracker
INSERT INTO projects (owner_id, title, description, tags, roadmap, project_embedding, status)
VALUES (
    (SELECT id FROM profiles WHERE email = 'alice@example.com'),
    'Campus Sustainability Challenge',
    'Gamified app to track and encourage sustainable behaviors on campus. Features include challenges, leaderboards, and carbon footprint tracking. Need mobile developers and backend experts.',
    ARRAY['sustainability', 'gamification', 'mobile', 'social-impact'],
    '{
        "frontend": [
            {"task": "Design challenge UI and leaderboards", "priority": "high", "estimated_hours": 18},
            {"task": "Create profile and stats screens", "priority": "high", "estimated_hours": 12}
        ],
        "backend": [
            {"task": "Build challenge and scoring system", "priority": "high", "estimated_hours": 16},
            {"task": "Implement social features", "priority": "medium", "estimated_hours": 10}
        ],
        "database": [
            {"task": "Design user actions and scoring schema", "priority": "high", "estimated_hours": 6}
        ],
        "estimated_total_hours": 62,
        "difficulty": "intermediate"
    }'::jsonb,
    (SELECT array_agg(0.0) FROM generate_series(1, 768))::vector,
    'open'
);

-- Verify data
SELECT 
    'Profiles inserted: ' || COUNT(*)::text as summary
FROM profiles;

SELECT 
    'Projects inserted: ' || COUNT(*)::text as summary
FROM projects;

-- Show sample data
SELECT 
    p.first_name || ' ' || p.last_name as name,
    p.major,
    p.experience_level,
    array_length(p.skills, 1) as num_skills
FROM profiles p
ORDER BY p.created_at;

SELECT 
    proj.title,
    prof.first_name || ' ' || prof.last_name as owner,
    array_length(proj.tags, 1) as num_tags,
    proj.status
FROM projects proj
JOIN profiles prof ON proj.owner_id = prof.id
ORDER BY proj.created_at;
